default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: excuse_me_flo

development:
  <<: *default
  database: excuse_me_flo_api_development

test:
  <<: *default
  database: excuse_me_flo_api_test

production:
  <<: *default
  database: excuse_me_flo_api_production
  password: <%= ENV['EXCUSE_ME_FLO_API_DATABASE_PASSWORD'] %>
